name: Pull Request

on:
  pull_request:
    branches: ["master"]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            8
            9

      - name: Restore tools
        run: dotnet tool restore
        shell: bash

      - name: Build projects
        run: |
          for sln in $(find . -name '*.sln'); do
            echo -e "\n\033[0;34mBuilding $sln \033[0m"
            dotnet build "$sln" -c Debug /p:WarningLevel=0
          done
        shell: bash

      - name: Run tests
        run: find . -name '*.Tests.csproj' | parallel --jobs 0 'echo -e "\n\033[0;34m{}\033[0m\n" && dotnet test {} -c Debug --no-build -p:"CollectCoverage=true" -p:"Exclude=[xunit.*]*" -p:"CoverletOutputFormat=opencover"'
        shell: bash
